### ISSUE TITLE
Cannot Compile in g++-6

### ISSUE THREAD

**Issue by rcalxrc08** [Tomius/auto_derive#1]
Hi,
hi cannot compile you simple example about your library,
the compiler states: 
`fatal error: ./cpp14.hpp: No such file or directory.`
I don't understand where that file should be.
I also tried to delete that include but then the compiler don't recognize `enable_if_t` statement.
I am compiling using `g++-6` 6.3.0.
I am using Linux Mint 18.1.
I obviusly added the right flag to the compiler, i.e. `-I../ -Icore/ -Itest -std=c++14`.
Do you have any idea?

**Comment by Tomius** [comment]
Hi rcalxrc08,

Thank you for letting me know this issue.

It seems that I forgot to commit that file, but there was only a using statement in it, like this:
```
template< bool B, class T = void >
using enable_if_t = typename std::enable_if<B,T>::type;
```

I first wanted this library to use c++11, not c++14, so I had to define this myself, and I somehow left it there.

Anyway, this issue seems to be fixed with the 2d78f536587a129ba3f4c220a223cd15758417db commit I just made.
